In [2]:
import torch

In [3]:
my_torch = torch.randn(10)
my_torch

tensor([ 0.1187,  1.0722,  0.2809, -1.2114, -0.2953, -0.3459, -0.6793,  1.5325,
        -0.3414, -0.2355])

In [4]:
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[ 0.1187,  1.0722,  0.2809, -1.2114, -0.2953],
        [-0.3459, -0.6793,  1.5325, -0.3414, -0.2355]])

In [5]:
### reshape if we don't know the number of items using -1
my_torch2 = torch.arange(20)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [6]:
my_torch2 = my_torch2.reshape(4, -1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [7]:
my_torch2 = my_torch2.reshape(-1, 2)
my_torch2

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]])

In [8]:
my_torch3 = my_torch2.view(2,10 )
my_torch3

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [9]:
### difffernce between shape and view?

In [10]:
my_torch8 = my_torch3.reshape(4,5)
my_torch8

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [11]:
my_torch8[:, 1]

tensor([ 1,  6, 11, 16])