### PyTorch Review and Practice

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


In [3]:
### Introduction to Tensors
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
### get tensor back as Python int
scalar.item()

7

In [6]:
### Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
### matrix
matrix = torch.tensor([[7, 8], [6, 5]])
matrix

tensor([[7, 8],
        [6, 5]])

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
matrix.ndim

2

In [12]:
matrix[1]

tensor([6, 5])

In [13]:
matrix[0][1]

tensor(8)

In [14]:
### tensor
tensor = torch.tensor([[[1, 2, 3],[4, 5, 6],[8, 9, 10]]])
tensor

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 8,  9, 10]]])

In [15]:
tensor.ndim

3

In [16]:
tensor.shape

torch.Size([1, 3, 3])

In [17]:
tensor[0]

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 8,  9, 10]])

In [43]:
### random tensors
random_tensor = torch.rand(3, 4, 2)
random_tensor

tensor([[[0.3776, 0.7787],
         [0.4018, 0.6334],
         [0.6965, 0.2777],
         [0.9286, 0.6468]],

        [[0.2104, 0.0244],
         [0.6054, 0.2301],
         [0.9687, 0.1375],
         [0.6432, 0.6691]],

        [[0.9786, 0.1874],
         [0.6722, 0.2188],
         [0.2306, 0.4973],
         [0.9396, 0.8043]]])

In [44]:
random_tensor.ndim

3

In [45]:
random_tensor.shape

torch.Size([3, 4, 2])

In [46]:
### create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(255, 255, 3)) ### height, wides, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([255, 255, 3]), 3)

In [47]:
### zeros and ones
zeros = torch.zeros(size=(3,4, 2))
torch.zeros

<function torch._VariableFunctionsClass.zeros>

In [48]:
zeros*random_tensor

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])

In [49]:
### create atensor of all ones
ones = torch.ones(size=(3,4, 2))
ones

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

In [25]:
ones.dtype, ones*random_tensor

(torch.float32,
 tensor([[[0.0335, 0.0411],
          [0.4225, 0.1247],
          [0.5693, 0.6502],
          [0.6941, 0.3491]],
 
         [[0.5259, 0.2311],
          [0.7193, 0.8604],
          [0.0813, 0.7204],
          [0.3583, 0.8515]],
 
         [[0.7267, 0.8270],
          [0.2857, 0.2555],
          [0.8470, 0.6722],
          [0.5625, 0.2151]]]))

In [26]:
### use torch.range()
one_to_ten = torch.arange(start= 1, end =11, step =2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [27]:
### create tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0])

In [29]:
### float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None,
                               device="cpu",
                               requires_grad=False)
float_32_tensor, float_32_tensor.dtype, float_32_tensor.device, float_32_tensor.requires_grad

(tensor([3., 6., 9.]), torch.float32, device(type='cpu'), False)

In [36]:
### tensor manipulations
random_tensor = torch.add(random_tensor, 10)
random_tensor, tensor.shape

(tensor([[[ 1010,  2010,  3010],
          [ 4010,  5010,  6010],
          [ 8010,  9010, 10010]]]),
 torch.Size([1, 3, 3]))

In [37]:
random_tensor = torch.mul(random_tensor, 10)
random_tensor, random_tensor.shape

(tensor([[[ 10100,  20100,  30100],
          [ 40100,  50100,  60100],
          [ 80100,  90100, 100100]]]),
 torch.Size([1, 3, 3]))

In [ ]:
### matrix multiplication
